version: '3'
services:
  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - './nginx-proxy-manager/data:/data'
      - './nginx-proxy-manager/letsencrypt:/etc/letsencrypt'
networks:
  default:
    external:
      name: wp-proxy-network
