version: '3'

services:
  db_dengiaothong:
    image: bitnami/mariadb:latest
    container_name: db_dengiaothong
    restart: unless-stopped
    env_file: .env
    volumes: 
      - dbdata_dengiaothong:/bitnami/mariadb

  opc_dengiaothong:  
    depends_on: 
      - db_dengiaothong
    image: bitnami/opencart:latest
    container_name: opc_dengiaothong
    restart: unless-stopped
    env_file: .env
    environment:
      - OPENCART_HOST=dengiaothong.net
      - OPENCART_DATABASE_HOST=db_dengiaothong
      - OPENCART_DATABASE_USER=$MARIADB_USER
      - OPENCART_DATABASE_PASSWORD=$MARIADB_PASSWORD
      - OPENCART_DATABASE_NAME=$MARIADB_DATABASE
    volumes:
      - ./opc_dengiaothong:/bitnami
      - ./setup:/opt/bitnami

volumes:
  dbdata_dengiaothong:

networks:
  default:
    name: wp-proxy-network
