version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db_{domain}
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: 258456cap
    networks:
      - internal-{domain}
  wordpress_{domain}:
    depends_on:
      - db_{domain}
    image: wordpress:latest
    container_name: wordpress_{domain}
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_{domain}:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 258456cap
    volumes:
      - ./webdata:/var/lib/html/
    networks:
      - nginx-network
      - internal-{domain}
networks:
  nginx-network:
    external: true
  internal-{domain}: