version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db_{domain}
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - internal-{domain}
  wordpress_{domain}:
    depends_on:
      - db_{domain}
    image: wordpress:latest
    container_name: wordpress_{domain}
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./webdata:/var/lib/html/
    networks:
      - nginx-network
      - internal-{domain}
networks:
  nginx-network:
    external: true
  internal-{domain}: