version: '3'
services:
  opencart_dengiaothong:
    image: chauanphu/opencart:4.0.2.1
    container_name: opencart_dengiaothong
    restart: unless-stopped
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - data-volume:/var/www/html
    depends_on:
      - db
    networks:
      - nginx-network
      - internal-dengiaothong
  db:
    container_name: db_dengiaothong
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=opencart
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD_ROOT}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - internal-dengiaothong

volumes:
  data-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./webdata

networks:
  nginx-network:
    external: true
  internal-dengiaothong: