version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=opencart
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1
    volumes:
      - webdata:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=opencart
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  webdata: