version: '3'
services:
  opencart_{domain}:
    image: chauanphu/opencart:1.0.2
    container_name: opencart_{domain}
    restart: unless-stopped
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=opencart
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1
    volumes:
      - data-volume:/var/www/html
    depends_on:
      - db
    networks:
      - nginx-network
      - internal-{domain}
  db:
    container_name: db_{domain}
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=opencart
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - internal-{domain}

volumes:
  data-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./webdata

networks:
  nginx-network:
    external: true
  internal-{domain}: